### ISSUE TITLE
GitLab and Bitbucket

### ISSUE THREAD

**Issue by pomber** [LuisReinoso/git-history-browser-extension#1]
Hey Luis, thanks for the extension. 
 
You may want to see if you can do the same for GitLab and Bitbucket, I'm planning to add support for those providers soon.

Also, we will support browsing directories inside of Git History, maybe the button should appeare there too.

**Comment by LuisReinoso** [comment]
Hi, @pomber.
Ok, Just tell me. How could urls be?. 
**gitlab**: https://gitlab.githistory.xyz/
**bitbucket**: https://bitbucket.githistory.xyz/?

To add a button in directories I think in two possible options

1. Button should be appear on all project path
https://git-provider.com/username/project-name/*

2. Button should be appear only when tree is in on path.
https://git-provider.com/username/project-name/tree/**

Second option, I think it's better because ensure is on git project. Tell me what do you think about this?

Cheers!

**Comment by pomber** [comment]
> **gitlab**: https://gitlab.githistory.xyz/
> **bitbucket**: https://bitbucket.githistory.xyz/?

:+1: 

> 2\. Button should be appear only when tree is in on path.
>    https://git-provider.com/username/project-name/tree/**

Second option seems better, it matches the behavior of the native GitHub "history" button.

**Comment by LuisReinoso** [comment]
@pomber Now this extension adds a button to gitlab and bitbucket, but I didn't publish it because in homepage: githistory.xyz says "GitLab and Bitbucket will come soon.".

Please, feel free to tell me when to publish this new version.

**Comment by pomber** [comment]
Thanks Luis! 
You can publish it now if you want. I'll update the home page and readme after I add some more stuff.

**Comment by LuisReinoso** [comment]
On firefox I can't publish today because 
> Add-on submission will be disabled on Monday, February 25th, due a planned server migration.

Google Chrome not have problem. I have published.

**Comment by LuisReinoso** [comment]
Ok, now I published on firefox!
